### ISSUE TITLE
Перевірка проксі

### ISSUE THREAD

**Issue by KarboDuck** [porthole-ascend-cinnamon/proxy_scraper#1]
Привіт. Чи є якійсь контакт? Розмірковуємо чи є сенс додавати рос. проксі. Треба протестувати чи витримають вони навантаження, там залізо не дуже. Додам ріквест з однією адресою до самого файлу проксі.

**Comment by porthole-ascend-cinnamon** [comment]
Привіт, я на зв'язку. Напиши дані тут або на пошту, я додам, бо цей файл перезаписується постійно.
